### ISSUE TITLE
About NoFrameskip.

### ISSUE THREAD

**Issue by firepd** [agopal42/permakey#1]
Hi, I am confused about NoFrameskip. It seems like the agent interacts with the environment for 400k steps (num_iters = 4 * 10 ** 5) due to NoFrameskip. Is there any particular reason to do this?

**Comment by JiangZhaoh** [comment]
I also think in fact the agent was trained with 400k steps instead of 100k. Although in code there is no frame stack, there will have a skip=4 when using baselines.atari_wrappers.make_atari.

**Comment by agopal42** [comment]
First of all I'd like to apologize for the extremely delayed response on my part!! 

Now with regards to your comment about the NoFrameskip. Your observation is correct our agent does indeed interact with the environment 400k times. However, our agent only performs 100k q-learning updates, with a ratio 1:4 of updates-to-interactions, whereas other implementations simply perform a q-learning update at every step of interaction (1:1 ratio). Please note, we did refer to this aspect in our Appendix A.2.3 "For eps-greedy exploration we linearly anneal from 1 to 0.1 over the entire 100,000 steps (or 400,000 frames)". Further, it is reasonable in my view to measure the sample-efficiency of an RL agent in terms of the number of update steps to the policy or value-function (starting from a random initialization) before evaluation is performed. In this regard, we remain consistent with prior work on training Atari agents in the low-data regime. 

Hope this provides some clarity! :)

**Comment by firepd** [comment]
Thanks for your reply and for the detailed explanations. I get it now.
